[tool.poetry]
name = "master-thesis"
version = "0.1.0"
description = ""
authors = ["Leonardo La Rocca <leo_la_rocca@yahoo.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
